[workspace]
members = ["rust_libs", "playground"]
exclude = ["rcore_os"]
resolver = "2"

[profile.release]
strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html