[workspace]
members = ["rust_libs", "playground", "neatpad_rs", "cg"]
resolver = "2"

[profile.release]
strip = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html